const questions = [
  {
    id: 1,
    title: "Popular cuisines near me",
    infos: [
      "Bakery food for tejasri near me • ",
      "Beverages food for tejasri near me • ",
      "Bihari food for tejasri near me • ",
      "Biryani food for tejasri near me • ",
      "Burger food for tejasri near me • ",
      "Chinese food for tejasri near me • ",
      "Desserts food for tejasri near me • ",
      "Ice Cream food for tejasri near me • ",
      "Kebab food for tejasri near me • ",
      "Momos food for tejasri near me • ",
      "Mughlai food for tejasri near me • ",
      "North Indian food for tejasri near me • ",
      "Pizza food for tejasri near me • ",
      "Rolls food for tejasri near me • ",
      "Sandwich food for tejasri near me • ",
      "Shake food for tejasri near me • ",
      "Sichuan food for tejasri near me • ",
      "South Indian food for tejasri near me • ",
      "Street food for tejasri near me • ",
    ],
  },
  {
    id: 2,
    title: "Popular restaurant types near me",
    infos: [
      "Bars near me • ",
      "Bakeries near me • ",
      "Beverage Shops near me • ",
      "Bhojanalya near me • ",
      "Cafés near me • ",
      "Casual Dining near me • ",
      "Confectioneries near me • ",
      "Dessert Parlors near me • ",
      "Dhabas near me • ",
      "Fine Dining near me • ",
      "food for tejasri Courts near me • ",
      "food for tejasri Trucks near me • ",
      "Kiosks near me • ",
      "Lounges near me • ",
      "Quick Bites near me • ",
      "Sweet Shops near me • ",
    ],
  },
  {
    id: 3,
    title: "Top Restaurant Chains",
    infos: [
      "KFC • ",
      "Paradise Biryani • ",
      "Pizza Hut • ",
      "Sagar RatnaWOW! • ",
      "Momo • ",
    ],
  },
];

export default questions;
